# Generated by Django 3.1.2 on 2021-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETL',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('YearWorkingPeriod', models.IntegerField(db_column='YearWorkingPeriod', verbose_name='سال-دوره')),
                ('HospitalDepartmentCode', models.IntegerField(db_column='HospitalDepartmentCode', verbose_name='کد بیمارستان')),
            ],
            options={
                'verbose_name': 'فرایند استخراج داده',
                'verbose_name_plural': 'فرایند استخراج داده',
                'db_table': 'nip_ETL',
            },
        ),
    ]
