# Generated by Django 3.1.2 on 2021-02-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_section',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basic_information.worksection'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(1, 'دانشگاه'), (2, 'بیمارستان'), (3, 'بخش ')], default=1),
        ),
    ]
