# Generated by Django 2.1.15 on 2020-08-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('PersianDate', models.CharField(max_length=10)),
                ('SpecialDay', models.IntegerField()),
                ('PersianYear', models.IntegerField()),
                ('PersianYearTitle', models.CharField(max_length=20)),
                ('FiscalYear', models.IntegerField()),
                ('WorkingPeriodYear', models.IntegerField(blank=True, null=True)),
                ('WorkingPeriod', models.IntegerField(blank=True, null=True)),
                ('WorkingPeriodTitle', models.CharField(blank=True, max_length=20, null=True)),
                ('PersianSemester', models.FloatField()),
                ('PersianSemesterTitle', models.CharField(max_length=20)),
                ('PersianQuarter', models.FloatField()),
                ('PersianQuarterTitle', models.CharField(max_length=20)),
                ('PersianMonth', models.FloatField()),
                ('PersianMonthTitle', models.CharField(max_length=20)),
                ('PersianWeekNumberOfYear', models.FloatField()),
                ('PersianWeekNumberOfMonth', models.FloatField()),
                ('PersianDayOfMonth', models.FloatField()),
                ('PersianDayOfYear', models.FloatField()),
                ('PersianWeekDay', models.FloatField()),
                ('PersianWeekDayTitle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'تاریخ',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelBaseId', models.IntegerField(verbose_name='PersonnelBaseId in Chargoon')),
                ('FullName', models.CharField(max_length=100)),
                ('YearWorkingPeriod', models.IntegerField()),
                ('RequirementWorkMins_esti', models.IntegerField()),
                ('RequirementWorkMins_real', models.IntegerField()),
                ('EfficiencyRolePoint', models.IntegerField()),
                ('DiffNorm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'پرسنل',
            },
        ),
        migrations.CreateModel(
            name='PersonnelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelBaseId', models.IntegerField(blank=True, null=True, verbose_name='PersonnelBaseId in Chargoon')),
                ('YearWorkingPeriod', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'درخواست خوداظهاری',
            },
        ),
        migrations.CreateModel(
            name='PersonnelShiftDateAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(null=True, verbose_name='سال-دوره')),
                ('D02', models.IntegerField(default=1, verbose_name='روز 02')),
                ('D03', models.IntegerField(default=1, verbose_name='روز 03')),
                ('D04', models.IntegerField(default=1, verbose_name='روز 04')),
                ('D05', models.IntegerField(default=1, verbose_name='روز 05')),
                ('D06', models.IntegerField(default=1, verbose_name='روز 06')),
                ('D07', models.IntegerField(default=1, verbose_name='روز 07')),
                ('D08', models.IntegerField(default=1, verbose_name='روز 08')),
                ('D09', models.IntegerField(default=1, verbose_name='روز 09')),
                ('D10', models.IntegerField(default=1, verbose_name='روز 10')),
                ('D11', models.IntegerField(default=1, verbose_name='روز 11')),
                ('D12', models.IntegerField(default=1, verbose_name='روز 12')),
                ('D13', models.IntegerField(default=1, verbose_name='روز 13')),
                ('D14', models.IntegerField(default=1, verbose_name='روز 14')),
                ('D15', models.IntegerField(default=1, verbose_name='روز 15')),
                ('D16', models.IntegerField(default=1, verbose_name='روز 16')),
                ('D17', models.IntegerField(default=1, verbose_name='روز 17')),
                ('D18', models.IntegerField(default=1, verbose_name='روز 18')),
                ('D19', models.IntegerField(default=1, verbose_name='روز 19')),
                ('D20', models.IntegerField(default=1, verbose_name='روز 20')),
                ('D21', models.IntegerField(default=1, verbose_name='روز 21')),
                ('D22', models.IntegerField(default=1, verbose_name='روز 22')),
                ('D23', models.IntegerField(default=1, verbose_name='روز 23')),
                ('D24', models.IntegerField(default=1, verbose_name='روز 24')),
                ('D25', models.IntegerField(default=1, verbose_name='روز 25')),
                ('D26', models.IntegerField(default=1, verbose_name='روز 26')),
                ('D27', models.IntegerField(default=1, verbose_name='روز 27')),
                ('D28', models.IntegerField(default=1, verbose_name='روز 28')),
                ('D29', models.IntegerField(default=1, verbose_name='روز 29')),
                ('D30', models.IntegerField(default=1, verbose_name='روز 30')),
                ('D31', models.IntegerField(default=1, verbose_name='روز 31')),
            ],
            options={
                'verbose_name_plural': 'جزئیات شیفت پیشنهادی',
            },
        ),
        migrations.CreateModel(
            name='PersonnelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'تخصص',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('EndTime', models.BigIntegerField(null=True)),
                ('UsedParentCount', models.IntegerField()),
                ('present_id', models.CharField(max_length=50, null=True, verbose_name='Presentation ID')),
            ],
            options={
                'verbose_name_plural': 'شیفت پیشنهادی',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Length', models.IntegerField()),
                ('StartTime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
                ('Type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Shift Type Code')),
            ],
            options={
                'verbose_name_plural': 'شیفت',
            },
        ),
        migrations.CreateModel(
            name='ShiftTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'نوع شیفت',
            },
        ),
        migrations.CreateModel(
            name='tkp_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Login', models.IntegerField()),
                ('Logout', models.IntegerField()),
                ('DayDisposition', models.IntegerField()),
                ('YearWorkingPeriodId', models.IntegerField()),
                ('LoginDayDisposition', models.IntegerField()),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'Time Logs',
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5)),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'واحد',
            },
        ),
        migrations.CreateModel(
            name='WorkSectionRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('DayType', models.IntegerField()),
                ('ReqMinCount', models.IntegerField()),
                ('ReqMaxCount', models.IntegerField()),
                ('day_diff_typ', models.IntegerField(blank=True, null=True)),
                ('Date', models.IntegerField(blank=True, null=True)),
                ('PersonnelTypeReqCount', models.IntegerField(blank=True, null=True)),
                ('PersonnelTypeReq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes')),
                ('WorkSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection')),
            ],
            options={
                'verbose_name_plural': 'WorkSection Requirements',
            },
        ),
        migrations.AddField(
            model_name='shiftassignments',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D01',
            field=models.ForeignKey(db_column='D01', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='Personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='ShiftAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftAssignments'),
        ),
        migrations.AddField(
            model_name='personnelrequest',
            name='ShiftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes'),
        ),
        migrations.AddField(
            model_name='personnelrequest',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='PersonnelTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
    ]
