# Generated by Django 2.1.15 on 2020-09-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('PersianDate', models.CharField(max_length=10)),
                ('SpecialDay', models.IntegerField()),
                ('PersianYear', models.IntegerField()),
                ('PersianYearTitle', models.CharField(max_length=20)),
                ('FiscalYear', models.IntegerField()),
                ('WorkingPeriodYear', models.IntegerField(blank=True, null=True)),
                ('WorkingPeriod', models.IntegerField(blank=True, null=True)),
                ('WorkingPeriodTitle', models.CharField(blank=True, max_length=20, null=True)),
                ('PersianSemester', models.FloatField()),
                ('PersianSemesterTitle', models.CharField(max_length=20)),
                ('PersianQuarter', models.FloatField()),
                ('PersianQuarterTitle', models.CharField(max_length=20)),
                ('PersianMonth', models.FloatField()),
                ('PersianMonthTitle', models.CharField(max_length=20)),
                ('PersianWeekNumberOfYear', models.FloatField()),
                ('PersianWeekNumberOfMonth', models.FloatField()),
                ('PersianDayOfMonth', models.FloatField()),
                ('PersianDayOfYear', models.FloatField()),
                ('PersianWeekDay', models.FloatField()),
                ('PersianWeekDayTitle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'تاریخ',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonnelBaseId', models.IntegerField(verbose_name='شناسه پرسنلی')),
                ('FullName', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('YearWorkingPeriod', models.IntegerField(editable=False, verbose_name='سال-دوره')),
                ('RequirementWorkMins_esti', models.IntegerField(verbose_name='زمان پیش بینی شده')),
                ('RequirementWorkMins_real', models.IntegerField(verbose_name='زمان اختصاص داده شده')),
                ('EfficiencyRolePoint', models.IntegerField(verbose_name='امتیاز بهره وری')),
                ('DiffNorm', models.IntegerField(blank=True, editable=False, null=True)),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
            ],
            options={
                'verbose_name_plural': 'پرسنل',
            },
        ),
        migrations.CreateModel(
            name='PersonnelLeaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(verbose_name='سال-دوره')),
                ('Day', models.IntegerField(verbose_name='روز')),
                ('Value', models.IntegerField(blank=True, null=True, verbose_name='مقدار')),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'پرسنل - مرخصی تایید شده',
            },
        ),
        migrations.CreateModel(
            name='PersonnelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(verbose_name='سال-دوره')),
                ('Day', models.IntegerField(verbose_name='روز')),
                ('Value', models.IntegerField(verbose_name='مقدار')),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'پرسنل - خوداظهاری',
            },
        ),
        migrations.CreateModel(
            name='PersonnelShiftDateAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(editable=False, null=True, verbose_name='سال-دوره')),
            ],
            options={
                'verbose_name_plural': 'شیفت پیشنهادی - آرشیو ',
            },
        ),
        migrations.CreateModel(
            name='PersonnelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5, verbose_name='کد')),
                ('Title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
            ],
            options={
                'verbose_name_plural': 'پرسنل - تخصص',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(editable=False, verbose_name='سال-دوره')),
                ('Rank', models.IntegerField(verbose_name='رتبه')),
                ('Cost', models.FloatField(verbose_name='هزینه')),
                ('EndTime', models.BigIntegerField(null=True, verbose_name='زمان تکمیل')),
                ('UsedParentCount', models.IntegerField(verbose_name='تعداد مصرف')),
                ('present_id', models.CharField(editable=False, max_length=50, null=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name_plural': 'شیفت پیشنهادی - جزئیات',
            },
        ),
        migrations.CreateModel(
            name='ShiftConstDayRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(verbose_name='روز')),
                ('ShiftTypes', models.IntegerField(db_column='ShiftTypes_id', verbose_name='نوع شیفت')),
                ('PersonnelCount', models.IntegerField(verbose_name='تعدا پرسنل اختصاص داده شده')),
                ('PersonnelPoints', models.IntegerField(verbose_name='مجموع امتیاز پرسنل')),
                ('RequireMinCount', models.IntegerField(verbose_name='حداقل تعداد نیاز')),
                ('RequireMaxCount', models.IntegerField(verbose_name='حداکثر تعاد نیاز')),
                ('RequireMeanCount', models.IntegerField(editable=False)),
                ('DiffMinCount', models.IntegerField(editable=False)),
                ('DiffMaxCount', models.IntegerField(editable=False)),
                ('DiffCount', models.IntegerField(verbose_name='اختلاف')),
                ('PersonnelTypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nip.PersonnelTypes')),
                ('ShiftAssignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftAssignments')),
            ],
            options={
                'verbose_name_plural': 'نیازمندی روزانه',
            },
        ),
        migrations.CreateModel(
            name='ShiftConstPersonnelTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EfficiencyRolePoint', models.IntegerField(verbose_name='امتیاز بهره وری')),
                ('RequireMinsEstimate', models.IntegerField(verbose_name='زمان نیاز بهره وری')),
                ('ExtraForce', models.IntegerField(null=True, verbose_name='مجمع زمان اجباری')),
                ('AssignedTimes', models.IntegerField(verbose_name='مقدار زمان اختصاص داده شده')),
                ('Diff', models.IntegerField(verbose_name='اختلاف')),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel')),
                ('PersonnelTypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nip.PersonnelTypes')),
                ('ShiftAssignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftAssignments')),
            ],
            options={
                'verbose_name_plural': 'اختلاف زمانی پرسنل',
            },
        ),
        migrations.CreateModel(
            name='ShiftRecommendManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(verbose_name='سال-دوره')),
                ('coh_const_DayRequirements', models.FloatField(verbose_name='ضریب قید نیاز روزانه')),
                ('coh_const_coh_PersonnelPerformanceTime', models.FloatField(verbose_name='ضریب قید نفرساعت بهره وری')),
                ('TaskStatus', models.IntegerField(choices=[(0, 'خاموش'), (1, 'روشن'), (2, 'بازیابی اطلاعات و اجرای مجدد')], default=0, verbose_name='وضعیت کل سیستم')),
                ('RecommenderStatus', models.IntegerField(choices=[(0, 'بهینه سازی'), (1, 'ایجاد جدید')], default=0, verbose_name='وضعیت پیشنهاددهنده')),
                ('PopulationSize', models.IntegerField(default=80, verbose_name='تعداد جمعیت')),
                ('GenerationCount', models.IntegerField(default=200, verbose_name='تعداد نسل')),
                ('MaxFitConstRate', models.FloatField(default=0.3, verbose_name='حداکثر نرخ ثبات هزینه')),
                ('CrossoverProbability', models.FloatField(default=0.3, verbose_name='نرخ جستجوی محلی')),
                ('MutationProbability', models.FloatField(default=0.3, verbose_name='نرخ جستجوی غیرمحلی')),
                ('Elitism', models.BooleanField(default=False, verbose_name='نابغه گرایی')),
                ('ShowPlot', models.BooleanField(default=False, verbose_name='نمایش نمودار هزینه')),
                ('DevByParent', models.BooleanField(default=True, verbose_name='توسعه والد')),
                ('TaskLevelDone', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'مدیریت - سیستم هوشمند شیفت',
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(verbose_name='کد')),
                ('Title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('Length', models.IntegerField(verbose_name='میزان')),
                ('StartTime', models.IntegerField(verbose_name='شروع')),
                ('EndTime', models.IntegerField(verbose_name='پایان')),
                ('Type', models.CharField(blank=True, max_length=3, null=True, verbose_name='نوع شیفت')),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
            ],
            options={
                'verbose_name_plural': 'شیفت',
            },
        ),
        migrations.CreateModel(
            name='ShiftTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5, verbose_name='کد')),
                ('Title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name_plural': 'نوع شیفت',
            },
        ),
        migrations.CreateModel(
            name='tkp_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Login', models.IntegerField()),
                ('Logout', models.IntegerField()),
                ('DayDisposition', models.IntegerField()),
                ('YearWorkingPeriodId', models.IntegerField()),
                ('LoginDayDisposition', models.IntegerField()),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nip.Personnel')),
            ],
            options={
                'verbose_name_plural': 'Time Logs',
            },
        ),
        migrations.CreateModel(
            name='WorkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=5, verbose_name='کد')),
                ('Title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('ExternalId', models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه')),
                ('ExternalGuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش',
            },
        ),
        migrations.CreateModel(
            name='WorkSectionRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(verbose_name='سال')),
                ('Month', models.IntegerField(verbose_name='دوره')),
                ('DayType', models.IntegerField(verbose_name='نوع روز')),
                ('ReqMinCount', models.IntegerField(verbose_name='حداقل')),
                ('ReqMaxCount', models.IntegerField(verbose_name='حداکثر')),
                ('day_diff_typ', models.IntegerField(blank=True, null=True, verbose_name='تفاوت')),
                ('Date', models.IntegerField(blank=True, null=True, verbose_name='تاریخ')),
                ('PersonnelTypeReqCount', models.IntegerField(blank=True, null=True, verbose_name='تعداد پرسنل')),
                ('PersonnelTypeReq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes')),
                ('WorkSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection')),
            ],
            options={
                'verbose_name_plural': 'بخش - نیزمندی ها',
            },
        ),
        migrations.AddField(
            model_name='shiftrecommendmanager',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='shiftassignments',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D01',
            field=models.ForeignKey(db_column='D01', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D02',
            field=models.ForeignKey(db_column='D02', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D02', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D03',
            field=models.ForeignKey(db_column='D03', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D03', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D04',
            field=models.ForeignKey(db_column='D04', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D04', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D05',
            field=models.ForeignKey(db_column='D05', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D05', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D06',
            field=models.ForeignKey(db_column='D06', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D06', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D07',
            field=models.ForeignKey(db_column='D07', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D07', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D08',
            field=models.ForeignKey(db_column='D08', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D08', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D09',
            field=models.ForeignKey(db_column='D09', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D09', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D10',
            field=models.ForeignKey(db_column='D10', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D10', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D11',
            field=models.ForeignKey(db_column='D11', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D11', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D12',
            field=models.ForeignKey(db_column='D12', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D12', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D13',
            field=models.ForeignKey(db_column='D13', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D13', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D14',
            field=models.ForeignKey(db_column='D14', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D14', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D15',
            field=models.ForeignKey(db_column='D15', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D15', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D16',
            field=models.ForeignKey(db_column='D16', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D16', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D17',
            field=models.ForeignKey(db_column='D17', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D17', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D18',
            field=models.ForeignKey(db_column='D18', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D18', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D19',
            field=models.ForeignKey(db_column='D19', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D19', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D20',
            field=models.ForeignKey(db_column='D20', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D20', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D21',
            field=models.ForeignKey(db_column='D21', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D21', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D22',
            field=models.ForeignKey(db_column='D22', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D22', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D23',
            field=models.ForeignKey(db_column='D23', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D23', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D24',
            field=models.ForeignKey(db_column='D24', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D24', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D25',
            field=models.ForeignKey(db_column='D25', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D25', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D26',
            field=models.ForeignKey(db_column='D26', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D26', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D27',
            field=models.ForeignKey(db_column='D27', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D27', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D28',
            field=models.ForeignKey(db_column='D28', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D28', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D29',
            field=models.ForeignKey(db_column='D29', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D29', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D30',
            field=models.ForeignKey(db_column='D30', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D30', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='D31',
            field=models.ForeignKey(db_column='D31', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D31', to='nip.Shifts'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='Personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.Personnel'),
        ),
        migrations.AddField(
            model_name='personnelshiftdateassignments',
            name='ShiftAssignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftAssignments'),
        ),
        migrations.AddField(
            model_name='personnelrequest',
            name='ShiftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.ShiftTypes'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='PersonnelTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.PersonnelTypes'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='WorkSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection'),
        ),
    ]
