# Generated by Django 2.1.15 on 2020-08-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0002_auto_20200804_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D01',
            field=models.ForeignKey(db_column='D01', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nip.Shifts'),
        ),
    ]
