# Generated by Django 2.1.15 on 2020-08-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0004_auto_20200804_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D03',
            field=models.ForeignKey(db_column='D03', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D03', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D04',
            field=models.ForeignKey(db_column='D04', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D04', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D05',
            field=models.ForeignKey(db_column='D05', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D05', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D06',
            field=models.ForeignKey(db_column='D06', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D06', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D07',
            field=models.ForeignKey(db_column='D07', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D07', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D08',
            field=models.ForeignKey(db_column='D08', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D08', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D09',
            field=models.ForeignKey(db_column='D09', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D09', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D10',
            field=models.ForeignKey(db_column='D10', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D10', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D11',
            field=models.ForeignKey(db_column='D11', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D11', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D12',
            field=models.ForeignKey(db_column='D12', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D12', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D13',
            field=models.ForeignKey(db_column='D13', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D13', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D14',
            field=models.ForeignKey(db_column='D14', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D14', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D15',
            field=models.ForeignKey(db_column='D15', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D15', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D16',
            field=models.ForeignKey(db_column='D16', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D16', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D17',
            field=models.ForeignKey(db_column='D17', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D17', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D18',
            field=models.ForeignKey(db_column='D18', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D18', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D19',
            field=models.ForeignKey(db_column='D19', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D19', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D20',
            field=models.ForeignKey(db_column='D20', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D20', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D21',
            field=models.ForeignKey(db_column='D21', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D21', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D22',
            field=models.ForeignKey(db_column='D22', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D22', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D23',
            field=models.ForeignKey(db_column='D23', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D23', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D24',
            field=models.ForeignKey(db_column='D24', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D24', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D25',
            field=models.ForeignKey(db_column='D25', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D25', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D26',
            field=models.ForeignKey(db_column='D26', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D26', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D27',
            field=models.ForeignKey(db_column='D27', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D27', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D28',
            field=models.ForeignKey(db_column='D28', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D28', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D29',
            field=models.ForeignKey(db_column='D29', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D29', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D30',
            field=models.ForeignKey(db_column='D30', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D30', to='nip.Shifts'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='D31',
            field=models.ForeignKey(db_column='D31', on_delete=django.db.models.deletion.DO_NOTHING, related_name='D31', to='nip.Shifts'),
        ),
    ]
