# Generated by Django 2.1.15 on 2020-08-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0006_personnelleaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelleaves',
            name='WorkSection',
        ),
        migrations.RemoveField(
            model_name='personnelrequest',
            name='WorkSection',
        ),
    ]
