# Generated by Django 2.1.15 on 2020-08-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0007_auto_20200830_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelleaves',
            name='PersonnelBaseId',
        ),
        migrations.RemoveField(
            model_name='personnelrequest',
            name='PersonnelBaseId',
        ),
    ]
