# Generated by Django 2.1.15 on 2020-08-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0008_auto_20200830_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelleaves',
            name='Value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
