# Generated by Django 2.1.15 on 2020-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0009_auto_20200830_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelleaves',
            options={'verbose_name_plural': 'پرسنل - مرخصی تایید شده'},
        ),
        migrations.AlterModelOptions(
            name='personnelrequest',
            options={'verbose_name_plural': 'پرسنل - خوداظهاری'},
        ),
        migrations.AlterModelOptions(
            name='personnelshiftdateassignments',
            options={'verbose_name_plural': 'شیفت پیشنهادی - جزئیات '},
        ),
        migrations.AlterModelOptions(
            name='personneltypes',
            options={'verbose_name_plural': 'پرسنل - تخصص'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignments',
            options={'verbose_name_plural': 'شیفت پیشنهادی - آرشیو'},
        ),
        migrations.AlterModelOptions(
            name='worksection',
            options={'verbose_name': 'بخش', 'verbose_name_plural': 'بخش'},
        ),
        migrations.AlterModelOptions(
            name='worksectionrequirements',
            options={'verbose_name_plural': 'بخش - نیزمندی ها'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='DiffNorm',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='EfficiencyRolePoint',
            field=models.IntegerField(verbose_name='امتیاز بهره وری'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='FullName',
            field=models.CharField(max_length=100, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='PersonnelBaseId',
            field=models.IntegerField(verbose_name='شناسه پرسنلی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='RequirementWorkMins_esti',
            field=models.IntegerField(verbose_name='زمان پیش بینی شده'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='RequirementWorkMins_real',
            field=models.IntegerField(verbose_name='زمان اختصاص داده شده'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='YearWorkingPeriod',
            field=models.IntegerField(editable=False, verbose_name='سال-دوره'),
        ),
        migrations.AlterField(
            model_name='personnelleaves',
            name='Day',
            field=models.IntegerField(verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='personnelleaves',
            name='Value',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='personnelleaves',
            name='YearWorkingPeriod',
            field=models.IntegerField(verbose_name='سال-دوره'),
        ),
        migrations.AlterField(
            model_name='personnelrequest',
            name='Day',
            field=models.IntegerField(verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='personnelrequest',
            name='Value',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='personnelrequest',
            name='YearWorkingPeriod',
            field=models.IntegerField(verbose_name='سال-دوره'),
        ),
        migrations.AlterField(
            model_name='personnelshiftdateassignments',
            name='YearWorkingPeriod',
            field=models.IntegerField(editable=False, null=True, verbose_name='سال-دوره'),
        ),
        migrations.AlterField(
            model_name='personneltypes',
            name='Code',
            field=models.CharField(max_length=5, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='personneltypes',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='Cost',
            field=models.FloatField(verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='EndTime',
            field=models.BigIntegerField(null=True, verbose_name='زمان تکمیل'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='Rank',
            field=models.IntegerField(verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='UsedParentCount',
            field=models.IntegerField(verbose_name='تعداد مصرف'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='YearWorkingPeriod',
            field=models.IntegerField(editable=False, verbose_name='سال-دوره'),
        ),
        migrations.AlterField(
            model_name='shiftassignments',
            name='present_id',
            field=models.CharField(editable=False, max_length=50, null=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='Code',
            field=models.IntegerField(verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='EndTime',
            field=models.IntegerField(verbose_name='پایان'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='Length',
            field=models.IntegerField(verbose_name='میزان'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='StartTime',
            field=models.IntegerField(verbose_name='شروع'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='Title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='Type',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='نوع شیفت'),
        ),
        migrations.AlterField(
            model_name='shifttypes',
            name='Code',
            field=models.CharField(max_length=5, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='shifttypes',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='Code',
            field=models.CharField(max_length=5, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='worksection',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='Date',
            field=models.IntegerField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='DayType',
            field=models.IntegerField(verbose_name='نوع روز'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='Month',
            field=models.IntegerField(verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='PersonnelTypeReqCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد پرسنل'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='ReqMaxCount',
            field=models.IntegerField(verbose_name='حداکثر'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='ReqMinCount',
            field=models.IntegerField(verbose_name='حداقل'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='Year',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='worksectionrequirements',
            name='day_diff_typ',
            field=models.IntegerField(blank=True, null=True, verbose_name='تفاوت'),
        ),
    ]
