# Generated by Django 2.1.15 on 2020-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0010_auto_20200908_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
        migrations.AddField(
            model_name='personnelleaves',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='personnelleaves',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
        migrations.AddField(
            model_name='personneltypes',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='personneltypes',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='shifts',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
        migrations.AddField(
            model_name='tkp_logs',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='tkp_logs',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
        migrations.AddField(
            model_name='worksection',
            name='ExternalGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شناسه شاخص دیدگاه'),
        ),
        migrations.AddField(
            model_name='worksection',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه دیدگاه'),
        ),
    ]
