# Generated by Django 2.1.15 on 2020-09-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0012_auto_20200915_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConstPersonnelTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EfficiencyRolePoint', models.IntegerField()),
                ('RequireMinsEstimate', models.IntegerField()),
                ('AssignedTimes', models.IntegerField()),
                ('Diff', models.IntegerField()),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nip.Personnel')),
                ('PersonnelTypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nip.PersonnelTypes')),
                ('ShiftAssignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nip.ShiftAssignments')),
            ],
            options={
                'verbose_name_plural': 'اختلاف زمانی پرسنل',
            },
        ),
    ]
