# Generated by Django 2.1.15 on 2020-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0014_auto_20200915_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftconstpersonneltimes',
            name='ExtraForce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='DiffMaxCount',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='DiffMinCount',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='RequireMeanCount',
            field=models.IntegerField(editable=False),
        ),
    ]
