# Generated by Django 2.1.15 on 2020-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0015_auto_20200915_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='Day',
            field=models.IntegerField(verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='DiffCount',
            field=models.IntegerField(verbose_name='اختلاف'),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='PersonnelCount',
            field=models.IntegerField(verbose_name='تعدا پرسنل اختصاص داده شده'),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='PersonnelPoints',
            field=models.IntegerField(verbose_name='مجموع امتیاز پرسنل'),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='RequireMaxCount',
            field=models.IntegerField(verbose_name='حداکثر تعاد نیاز'),
        ),
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='RequireMinCount',
            field=models.IntegerField(verbose_name='حداقل تعداد نیاز'),
        ),
        migrations.AlterField(
            model_name='shiftconstpersonneltimes',
            name='AssignedTimes',
            field=models.IntegerField(verbose_name='مقدار زمان اختصاص داده شده'),
        ),
        migrations.AlterField(
            model_name='shiftconstpersonneltimes',
            name='Diff',
            field=models.IntegerField(verbose_name='اختلاف'),
        ),
        migrations.AlterField(
            model_name='shiftconstpersonneltimes',
            name='EfficiencyRolePoint',
            field=models.IntegerField(verbose_name='امتیاز بهره وری'),
        ),
        migrations.AlterField(
            model_name='shiftconstpersonneltimes',
            name='ExtraForce',
            field=models.IntegerField(null=True, verbose_name='مجمع زمان اجباری'),
        ),
        migrations.AlterField(
            model_name='shiftconstpersonneltimes',
            name='RequireMinsEstimate',
            field=models.IntegerField(verbose_name='زمان نیاز بهره وری'),
        ),
    ]
