# Generated by Django 2.1.15 on 2020-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0016_auto_20200915_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='ShiftTypes',
            field=models.IntegerField(),
        ),
    ]
