# Generated by Django 2.1.15 on 2020-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0017_auto_20200916_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='ShiftTypes',
            field=models.IntegerField(verbose_name='نوع شیفت'),
        ),
    ]
