# Generated by Django 2.1.15 on 2020-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0018_auto_20200916_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftconstdayrequirements',
            name='ShiftTypes',
            field=models.IntegerField(db_column='ShiftTypes_id', verbose_name='نوع شیفت'),
        ),
    ]
