# Generated by Django 2.1.15 on 2020-09-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0019_auto_20200916_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelshiftdateassignments',
            options={'verbose_name_plural': 'شیفت پیشنهادی - آرشیو '},
        ),
        migrations.AlterModelOptions(
            name='shiftassignments',
            options={'verbose_name_plural': 'شیفت پیشنهادی - جزئیات'},
        ),
    ]
