# Generated by Django 2.1.15 on 2020-09-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0021_shiftrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRecommanderAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearWorkingPeriod', models.IntegerField(verbose_name='سال-دوره')),
                ('coh_const_DayRequirements', models.FloatField(verbose_name='ضریب قید نیاز روزانه')),
                ('coh_const_coh_PersonnelPerformanceTime', models.FloatField(verbose_name='ضریب قید نفرساعت بهره وری')),
                ('CreateNew', models.BooleanField(choices=[(0, 'بهینه سازی'), (1, 'ایجاد جدید')], default=0, verbose_name='نوع ایجاد')),
                ('PopulationSize', models.IntegerField(default=80, verbose_name='تعداد جمعیت')),
                ('GenerationCount', models.IntegerField(default=200, verbose_name='تعداد نسل')),
                ('MaxFitConstRate', models.FloatField(default=0.3, verbose_name='حداکثر نرخ ثبات هزینه')),
                ('CrossoverProbability', models.FloatField(default=0.3, verbose_name='نرخ جستجوی محلی')),
                ('MutationProbability', models.FloatField(default=0.3, verbose_name='نرخ جستجوی غیرمحلی')),
                ('Elitism', models.BooleanField(default=False, verbose_name='نابغه گرایی')),
                ('ShowPlot', models.BooleanField(default=False, verbose_name='نمایش نمودار هزینه')),
                ('DevByParent', models.BooleanField(default=True, verbose_name='توسعه والد')),
                ('WorkSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nip.WorkSection')),
            ],
            options={
                'verbose_name_plural': 'مدیریت - سیستم هوشمند شیفت',
            },
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='WorkSection',
        ),
        migrations.DeleteModel(
            name='ShiftRequest',
        ),
    ]
