# Generated by Django 2.1.15 on 2020-09-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0022_auto_20200916_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftRecommanderAdmin',
            new_name='ShiftRecommandManager',
        ),
    ]
