# Generated by Django 2.1.15 on 2020-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0023_auto_20200916_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrecommandmanager',
            name='Status',
            field=models.IntegerField(choices=[(0, 'خاموش'), (1, 'درحال اجرا'), (2, 'متوقف شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shiftrecommandmanager',
            name='CreateNew',
            field=models.IntegerField(choices=[(0, 'بهینه سازی'), (1, 'ایجاد جدید')], default=0, verbose_name='نوع ایجاد'),
        ),
    ]
