# Generated by Django 2.1.15 on 2020-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0024_auto_20200916_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrecommandmanager',
            name='CreateNew',
        ),
        migrations.RemoveField(
            model_name='shiftrecommandmanager',
            name='Status',
        ),
        migrations.AddField(
            model_name='shiftrecommandmanager',
            name='RecommanderStatus',
            field=models.IntegerField(choices=[(0, 'بهینه سازی'), (1, 'ایجاد جدید')], default=0, verbose_name='وضعیت پیشنهاددهنده'),
        ),
        migrations.AddField(
            model_name='shiftrecommandmanager',
            name='TaskLevelDone',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='shiftrecommandmanager',
            name='TaskStatus',
            field=models.IntegerField(choices=[(0, 'خاموش'), (1, 'روشن'), (2, 'بازیابی اطلاعات و اجرای مجدد')], default=0, verbose_name='وضعیت کل سیستم'),
        ),
    ]
